In [1]:
from gensim.models import Word2Vec, KeyedVectors

In [2]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [3]:
from nltk.tokenize import word_tokenize

In [4]:
import pandas as pd
df = pd.read_csv('Data.txt', sep='\t', names = ['label', 'message'])

In [10]:
lemmatizer = WordNetLemmatizer()

In [21]:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-z]',' ', df['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english') and len(word) > 2]
    corpus.append(review)

In [22]:
import gensim
model = gensim.models.Word2Vec(corpus)

In [23]:
model.wv.index_to_key

['call',
 'get',
 'day',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'love',
 'text',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'phone',
 'new',
 'later',
 'please',
 'pls',
 'msg',
 'min',
 'dear',
 'night',
 'make',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'hope',
 'claim',
 'great',
 'hey',
 'number',
 'give',
 'happy',
 'work',
 'friend',
 'wat',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'tone',
 'said',
 'ask',
 'win',
 'amp',
 'cash',
 'life',
 'yeah',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'last',
 'service',
 'year',
 'thanks',
 'care',
 'co',
 'would',
 'anything',
 'com',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'something',
 'gud',
 'buy',
 'cant',
 'wait',
 'box',
 'place',
 'first',
 'even',
 'guy',
 'someone',
 'help',
 'went',
 'wish',
 'nice',
 'next',
 'tonight',
 'show',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'sm',
 'always',
 'gonna',
 'wan',
 'leave',
 'name',
 'lot',
 'end',
 'dun',
 'told',
 'person',
 'waiting',
 'special',
 'hello',
 'girl',
 'try',
 'fine',
 'month',
 'hour',
 'may',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'best',
 'thk',
 'yet',
 'guaranteed',
 'smile',
 'done',
 'getting',
 'god',
 'ppm',
 'thought',
 'use',
 'offer',
 'start',
 'holiday',
 'class',
 'stuff',
 'talk',
 'line',
 'mean',
 'bit',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'draw',
 'job',
 'finish',
 'problem',
 'never',
 'plan',
 'ill',
 'house',
 'better',
 'cool',
 'thats',
 'meeting',
 'trying',
 'yup',
 'mind',
 'ready',
 'dat',
 'account',
 'long',
 'pobox',
 'rate',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'real',
 'half',
 'latest',
 'world',
 'sir',
 'guess',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'luv',
 'nothing',
 'wanna',
 'awarded',
 'sweet',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'landline',
 'birthday',
 'dinner',
 'xxx',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'jus',
 'age',
 'hr',
 'land',
 'watch',
 'watching',
 'wont',
 'question',
 'probably',
 'orange',
 'two',
 'baby',
 'thanx',
 'called',
 'dream',
 'worry',
 'aight',
 'bed',
 'hear',
 'speak',
 'fun',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'shall',
 'nite',
 'forgot',
 'part',
 'maybe',
 'ringtone',
 'left',
 'bus',
 'pay',
 'remember',
 'network',
 'apply',
 'office',
 'dunno',
 'made',
 'shopping',
 'reach',
 'easy',
 'hurt',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'true',
 'didnt',
 'everything',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'anyway',
 'dis',
 'mate',
 'town',
 'gift',
 'sound',
 'working',
 'mail',
 'school',
 'movie',
 'afternoon',
 'looking',
 'thank',
 'enough',
 'selected',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'pound',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'pain',
 'since',
 'wanted',
 'valid',
 'though',
 'wif',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'run',
 'missed',
 'lesson',
 'go',
 'plus',
 'away',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'wen',
 'date',
 'attempt',
 'bored',
 'dude',
 'weekly',
 'music',
 'shop',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'update',
 'lei',
 'goin',
 'online',
 'drink',
 'friendship',
 'optout',
 'oso',
 'coz',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'credit',
 'net',
 'colour',
 'family',
 'sch',
 'either',
 'feeling',
 'club',
 'hot',
 'smoke',
 'player',
 'address',
 'driving',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'walk',
 'story',
 'believe',
 'order',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'happen',
 'noe',
 'sleeping',
 'hand',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'wil',
 'awesome',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'aft',
 'news',
 'auction',
 'anyone',
 'neva',
 'mine',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'company',
 'break',
 'touch',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'available',
 'alone',
 'loving',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'found',
 'si',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'hows',
 'party',
 'fast',
 'sub',
 'visit',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'hard',
 'ltd',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'project',
 'light',
 'read',
 'hold',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'wit',
 'operator',
 'used',
 'camcorder',
 'crazy',
 'support',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'meant',
 'case',
 'course',
 'log',
 'hmm',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'knew',
 'yr',
 'understand',
 'store',
 'mayb',
 'sell',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'within',
 'park',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'load',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'an',
 'darren',
 'kid',
 'gym',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'doin',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'swing',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'gotta',
 'complimentary',
 'correct',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'nobody',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'yep',
 'slow',
 'discount',
 'weed',
 'small',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'lover',
 'road',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'red',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'cover',
 'write',
 'ringtones',
 'energy',
 'doctor',
 'convey',
 'sale',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'king',
 'indian',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'near',
 'water',
 'different',
 'booked',
 'ldn',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'usual',
 'deep',
 'admirer',
 'kick',
 'street',
 'teach',
 'deal',
 'bathe',
 'spend',
 'pray',
 'sony',
 'del',
 'men',
 'gave',
 'representative',
 'short',
 'forever',
 'situation',
 'reached',
 'oops',
 'catch',
 'turn',
 'worried',
 'england',
 'copy',
 'callertune',
 'nah',
 'cup',
 'tear',
 'sofa',
 'colleague',
 'flag',
 'sitting',
 'thinkin',
 'excuse',
 'excellent',
 'moral',
 'reaching',
 'tht',
 'others',
 'wondering',
 'mode',
 'mon',
 'digital',
 'hiya',
 'iam',
 'gay',
 'user',
 'tampa',
 'fall',
 'charity',
 'comuk',
 'bid',
 'norm',
 'possible',
 'add',
 'seems',
 'bold',
 'starting',
 'forwarded',
 'hotel',
 'self',
 'silent',
 'meh',
 'style',
 'result',
 'kinda',
 'voice',
 'logo',
 'none',
 'brings',
 'reference',
 'bluetooth',
 'urself',
 'round',
 'rcvd',
 'access',
 'cake',
 'accept',
 'sport',
 'rose',
 'unless',
 'disturb',
 'ldew',
 'goodnight',
 'ive',
 'mrt',
 'dead',
 'using',
 'trust',
 'studying',
 'especially',
 'doesnt',
 'staying',
 'completely',
 'lect',
 'lazy',
 'sunshine',
 'buying',
 'ending',
 'flight',
 'specially',
 'bos',
 'coffee',
 'password',
 'rain',
 'stand',
 'ice',
 'decide',
 'sick',
 'seriously',
 'issue',
 'mood',
 'pix',
 'wednesday',
 'list',
 'inside',
 'south',
 'fill',
 'frens',
 'dog',
 'picked',
 'honey',
 'complete',
 'cute',
 'cancel',
 'awaiting',
 'black',
 'fight',
 'miracle',
 'medical',
 'registered',
 'training',
 'polys',
 'moon',
 'omg',
 'slave',
 'space',
 'library',
 'student',
 'bedroom',
 'tuesday',
 'longer',
 'alex',
 'future',
 'euro',
 'present',
 'daddy',
 'workin',
 'finger',
 'fat',
 'realy',
 'thru',
 'din',
 'giving',
 'funny',
 'aha',
 'yahoo',
 'fullonsms',
 'facebook',
 'picture',
 'fault',
 'interested',
 'wiv',
 'fixed',
 'woman',
 'record',
 'power',
 'lemme',
 'ppmx',
 'sign',
 'file',
 'slept',
 'however',
 'joined',
 'freephone',
 'goto',
 'sometimes',
 'shirt',
 'swt',
 'dvd',
 'bak',
 'paying',
 'inc',
 'apartment',
 'weight',
 'umma',
 'ave',
 ...]

In [24]:
model.wv.most_similar('free')

[('mobile', 0.9996051788330078),
 ('text', 0.9995541572570801),
 ('reply', 0.9994907379150391),
 ('win', 0.9994864463806152),
 ('week', 0.9994817972183228),
 ('txt', 0.9994676113128662),
 ('cash', 0.9994529485702515),
 ('tone', 0.9994293451309204),
 ('min', 0.9994168281555176),
 ('phone', 0.9994069933891296)]

In [30]:
model.wv.most_similar('glad')

[('enjoy', 0.9939649701118469),
 ('mind', 0.9939519762992859),
 ('liao', 0.9938578009605408),
 ('wait', 0.9937649965286255),
 ('fine', 0.993645191192627),
 ('work', 0.9936420917510986),
 ('month', 0.9936038851737976),
 ('life', 0.9935886859893799),
 ('need', 0.9935715198516846),
 ('good', 0.9935311675071716)]

In [31]:
import numpy as np

def avg_word2vec(sentence, model):
    vectors = []

    for word in sentence:
        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [32]:
X = []
for sentence in corpus:
    vector = avg_word2vec(sentence, model)
    X.append(vector)

In [33]:
X

[array([-0.16588521,  0.12413815,  0.03501731,  0.01591281,  0.00442398,
        -0.38769487,  0.10074645,  0.5231509 , -0.1407719 , -0.05090433,
        -0.14591932, -0.16788833, -0.08503249,  0.05945468,  0.06552453,
        -0.11510771, -0.03438608, -0.3207294 , -0.02175837, -0.438149  ,
         0.15127838,  0.17311947,  0.07319544, -0.07937916, -0.0800223 ,
        -0.06872602, -0.24251872, -0.21956092, -0.25954187,  0.01021356,
         0.2722863 ,  0.03862719,  0.11629926, -0.10738739, -0.04564457,
         0.30210364, -0.00709407, -0.19058865, -0.17143847, -0.43425015,
         0.00855908, -0.13579609, -0.04554378, -0.036313  ,  0.17709287,
        -0.03175293, -0.08092511,  0.01236854,  0.11966427,  0.17542632,
         0.10438511, -0.17343736, -0.0150277 ,  0.04790331, -0.12790574,
         0.16727048,  0.1686385 , -0.03727133, -0.23957688,  0.06520837,
         0.08260134,  0.08745333,  0.0219578 , -0.02651541, -0.29563296,
         0.0862752 ,  0.12099896,  0.17384487, -0.22758678,  0.24987714,
        -0.16139239,  0.13394514,  0.26078492, -0.0531657 ,  0.25863203,
         0.08481222, -0.00356247, -0.10039218, -0.26301518,  0.07560933,
        -0.06424319,  0.00192375, -0.1840275 ,  0.38814762, -0.04960687,
         0.05824398,  0.03252698,  0.33748287,  0.2627343 ,  0.06109549,
         0.24825811,  0.17717828, -0.00871148,  0.05265153,  0.3893153 ,
         0.24369209,  0.1359308 , -0.24379796,  0.08434281, -0.13045852],
       dtype=float32),
 array([-0.11690027,  0.08820324,  0.02538487,  0.01292075,  0.00240942,
        -0.26708654,  0.06855617,  0.3691739 , -0.0959387 , -0.03551741,
        -0.10159311, -0.11376695, -0.06190668,  0.04016839,  0.04424372,
        -0.0816307 , -0.02728436, -0.22589207, -0.01815525, -0.3071806 ,
         0.1038842 ,  0.12370745,  0.04855205, -0.0538637 , -0.05842708,
        -0.05463442, -0.1725346 , -0.15666336, -0.18676461,  0.00383377,
         0.19472452,  0.03075391,  0.08140047, -0.07416374, -0.03038727,
         0.21255732, -0.00937751, -0.13467787, -0.12146243, -0.3058306 ,
         0.00442846, -0.09658136, -0.03390295, -0.01859424,  0.12595375,
        -0.02645816, -0.05626817,  0.00765542,  0.08524085,  0.11802248,
         0.08091334, -0.11850055, -0.01541037,  0.02933796, -0.09466229,
         0.12024917,  0.11573847, -0.02416645, -0.17263395,  0.03975919,
         0.05246046,  0.05592557,  0.01712533, -0.01751713, -0.20287065,
         0.06555466,  0.09071057,  0.11960914, -0.15977715,  0.17517672,
        -0.11029854,  0.09897962,  0.18320154, -0.03744219,  0.17432941,
         0.05678434, -0.00276946, -0.07549935, -0.18285425,  0.05457664,
        -0.04545118, -0.00551117, -0.12382068,  0.264648  , -0.03418951,
         0.04494802,  0.02157486,  0.23846434,  0.18359989,  0.04483686,
         0.17715222,  0.11459681, -0.00149131,  0.03541315,  0.2669129 ,
         0.176264  ,  0.09690977, -0.17720573,  0.06354176, -0.08615572],
       dtype=float32),
 array([-0.19416678,  0.13948834,  0.03996133,  0.02118893,  0.01095683,
        -0.4490693 ,  0.11938441,  0.6120621 , -0.15991275, -0.0664848 ,
        -0.17497653, -0.1898766 , -0.10182899,  0.06772051,  0.07564822,
        -0.1325123 , -0.04105233, -0.37682667, -0.03068792, -0.52000004,
         0.18011041,  0.20754075,  0.09125146, -0.09185356, -0.0975436 ,
        -0.07446086, -0.2807737 , -0.24913822, -0.2911758 ,  0.02304151,
         0.30559874,  0.04216415,  0.13766082, -0.13116607, -0.0543991 ,
         0.34759083, -0.01115863, -0.22499125, -0.2129835 , -0.5012282 ,
         0.00243367, -0.1544228 , -0.0430648 , -0.04446057,  0.21665716,
        -0.03327766, -0.09161631,  0.01192811,  0.1340291 ,  0.20822375,
         0.12031288, -0.20026173, -0.02304903,  0.05314938, -0.14263901,
         0.1854886 ,  0.19102854, -0.04126828, -0.28574988,  0.0809461 ,
         0.09642597,  0.10095525,  0.02147301, -0.03036126, -0.34458068,
         0.10489961,  0.14816104,  0.20763661, -0.26090252,  0.29315194,
        -0.17963664,  0.15294655,  0.3031764 , -0.05314794,  0.2999504 ,
         0.09120108, -0.0046258 , -0.11313725, -0.29866564,  0.08360027,
        -0.07701495,  0.00396601, -0.2155771 ,  0.45088887, -0.04829445,
         0.07178055,  0.03973874,  0.39473587,  0.2936824 ,  0.06345006,
         0.28813082,  0.19448625, -0.00704663,  0.06525994,  0.4484929 ,
         0.27891207,  0.15736037, -0.28568134,  0.08877648, -0.14405298],
       dtype=float32),
 array([-0.2571527 ,  0.19380257,  0.05656379,  0.02639968,  0.01500198,
        -0.5962658 ,  0.1512918 ,  0.8042224 , -0.21478792, -0.07818662,
        -0.23508891, -0.26283568, -0.12197658,  0.09265232,  0.10652175,
        -0.18341398, -0.05084208, -0.49395102, -0.03270221, -0.6689812 ,
         0.23028222,  0.2726822 ,  0.11508145, -0.11623295, -0.12643036,
        -0.10439976, -0.37999862, -0.3336413 , -0.40527934,  0.01970703,
         0.42244545,  0.05432922,  0.18094358, -0.16302475, -0.07377496,
         0.46910396, -0.01721575, -0.3043539 , -0.272018  , -0.6670972 ,
         0.00597218, -0.21029043, -0.06523427, -0.0532945 ,  0.26455793,
        -0.05165397, -0.12846358,  0.02213596,  0.18840106,  0.2663812 ,
         0.16558887, -0.27584228, -0.0271536 ,  0.07257316, -0.2017661 ,
         0.25719604,  0.25777963, -0.05536281, -0.37235516,  0.09555435,
         0.13382065,  0.12951319,  0.03202116, -0.03595841, -0.45793486,
         0.13784772,  0.19528373,  0.26644522, -0.35531205,  0.39678594,
        -0.24745703,  0.20573857,  0.41076607, -0.07739234,  0.4041399 ,
         0.12930377, -0.0053041 , -0.15927471, -0.40217486,  0.11680692,
        -0.10819541, -0.00280285, -0.28301576,  0.60063666, -0.08422425,
         0.09056948,  0.05450924,  0.525369  ,  0.408909  ,  0.09120671,
         0.38830152,  0.2665655 , -0.01351659,  0.07325157,  0.5881599 ,
         0.36990207,  0.21652016, -0.3838386 ,  0.12554953, -0.20620075],
       dtype=float32),
 array([-0.17301014,  0.12676181,  0.03662443,  0.01892811,  0.00548064,
        -0.39063194,  0.10958923,  0.53960764, -0.1417128 , -0.05350007,
        -0.15155457, -0.1753424 , -0.08265923,  0.05787004,  0.06864569,
        -0.12068865, -0.03421367, -0.32778975, -0.02043984, -0.45273265,
         0.15641136,  0.17716476,  0.07094068, -0.08407479, -0.07838726,
        -0.07031403, -0.2502187 , -0.2283386 , -0.2705012 ,  0.01297469,
         0.27712148,  0.03843514,  0.11767455, -0.10983281, -0.04671922,
         0.30770922, -0.00903157, -0.19586065, -0.1800393 , -0.44449374,
         0.00787549, -0.14439581, -0.0465637 , -0.03545169,  0.18195224,
        -0.03709148, -0.08615539,  0.01372701,  0.12684582,  0.18168218,
         0.10756349, -0.17729306, -0.02073045,  0.05461742, -0.13488388,
         0.17277409,  0.17419532, -0.04045295, -0.25033945,  0.06436983,
         0.09297551,  0.08933168,  0.02422561, -0.03165264, -0.30446163,
         0.09040857,  0.12913589,  0.17938413, -0.23642755,  0.2601256 ,
        -0.16156793,  0.1407351 ,  0.27292493, -0.04693243,  0.26802862,
         0.08626004, -0.00395188, -0.10519544, -0.2709204 ,  0.07670414,
        -0.06754727, -0.00214518, -0.18935673,  0.39985847, -0.05431226,
         0.06291575,  0.03267128,  0.3474172 ,  0.2715184 ,  0.06282274,
         0.25495678,  0.17575513, -0.00817352,  0.04960089,  0.39765793,
         0.24912557,  0.13958572, -0.25317994,  0.08582158, -0.1330016 ],
       dtype=float32),
 array([-2.05618694e-01,  1.48306325e-01,  4.41532880e-02,  2.05572676e-02,
         7.89344590e-03, -4.74110514e-01,  1.25947252e-01,  6.44306958e-01,
        -1.74028262e-01, -6.63314983e-02, -1.83039412e-01, -2.06161976e-01,
        -1.03820421e-01,  7.21895695e-02,  8.18436742e-02, -1.38510823e-01,
        -4.00807299e-02, -3.90638709e-01, -2.99572144e-02, -5.47962844e-01,
         1.85800329e-01,  2.17996582e-01,  9.41645205e-02, -1.00413881e-01,
        -1.01592474e-01, -7.93819651e-02, -3.03248614e-01, -2.72382230e-01,
        -3.14313084e-01,  1.80583466e-02,  3.32863897e-01,  4.76964712e-02,
         1.46214679e-01, -1.34154692e-01, -5.67162894e-02,  3.70184034e-01,
        -1.72569882e-02, -2.38488197e-01, -2.15406522e-01, -5.33591926e-01,
         6.28821785e-03, -1.67295769e-01, -5.14712743e-02, -4.55515496e-02,
         2.24631354e-01, -4.44298834e-02, -1.02027304e-01,  1.06858453e-02,
         1.47954926e-01,  2.17206523e-01,  1.31080955e-01, -2.13203713e-01,
        -2.38590483e-02,  5.91679811e-02, -1.54995084e-01,  2.03047574e-01,
         2.08125174e-01, -4.36495394e-02, -2.98128575e-01,  8.43325183e-02,
         1.02773152e-01,  1.04082324e-01,  2.88638696e-02, -3.36979181e-02,
        -3.67094129e-01,  1.10954918e-01,  1.56052157e-01,  2.13837028e-01,
        -2.80768216e-01,  3.14500004e-01, -1.97491333e-01,  1.61071822e-01,
         3.22385728e-01, -5.78397773e-02,  3.17167252e-01,  9.76214036e-02,
        -6.60688244e-03, -1.21640868e-01, -3.21575016e-01,  9.12193432e-02,
        -8.11318159e-02, -6.06996706e-04, -2.27488473e-01,  4.78911877e-01,
        -5.80967031e-02,  7.73427263e-02,  4.09563519e-02,  4.18093771e-01,
         3.22152287e-01,  7.01014623e-02,  3.06567341e-01,  2.09423050e-01,
        -6.82152761e-03,  6.36734739e-02,  4.74914223e-01,  2.96025336e-01,
         1.72093377e-01, -3.03752393e-01,  9.81751904e-02, -1.58950165e-01],
       dtype=float32),
 array([-0.2107632 ,  0.15691303,  0.04772854,  0.01935263,  0.00541285,
        -0.4969778 ,  0.13992135,  0.6780012 , -0.1795624 , -0.06759562,
        -0.19484417, -0.2193058 , -0.10807065,  0.08047584,  0.08476793,
        -0.1535459 , -0.03482347, -0.41330287, -0.02406716, -0.57327384,
         0.19695164,  0.22963913,  0.09990422, -0.10455052, -0.10661148,
        -0.08301234, -0.32133985, -0.29024372, -0.3362926 ,  0.01291308,
         0.35413912,  0.05644618,  0.14867051, -0.13378125, -0.06300735,
         0.39234242, -0.01699015, -0.2544082 , -0.22720903, -0.5634877 ,
         0.00750921, -0.18222244, -0.05524603, -0.05355088,  0.23727734,
        -0.04207996, -0.11328766,  0.01183341,  0.15613005,  0.22327042,
         0.13996235, -0.22990645, -0.02345867,  0.06515452, -0.17091274,
         0.21182565,  0.21258235, -0.05305936, -0.31756482,  0.07726644,
         0.11026296,  0.10763243,  0.030916  , -0.03423461, -0.38473335,
         0.11816403,  0.15844043,  0.22389813, -0.29656604,  0.32803658,
        -0.20848997,  0.1753366 ,  0.3415705 , -0.06247972,  0.33677185,
         0.10020926, -0.00571289, -0.12885329, -0.34162006,  0.10338861,
        -0.08364008, -0.00252473, -0.24532767,  0.50686926, -0.06859908,
         0.07358655,  0.04692704,  0.44412133,  0.34008265,  0.07375767,
         0.32118037,  0.21963578, -0.00913844,  0.06528626,  0.5021765 ,
         0.31532347,  0.1802268 , -0.3238455 ,  0.10745437, -0.16886675],
       dtype=float32),
 array([-0.13057497,  0.09705424,  0.02712868,  0.01315534,  0.00338784,
        -0.30508795,  0.08301785,  0.41795748, -0.10589384, -0.04292886,
        -0.12022243, -0.13386428, -0.06941142,  0.0475863 ,  0.05640484,
        -0.08799309, -0.02879831, -0.2527433 , -0.0177759 , -0.3480446 ,
         0.12590958,  0.13778026,  0.05542665, -0.06488916, -0.06732437,
        -0.04906943, -0.19312105, -0.17319351, -0.20554823,  0.01248096,
         0.21183357,  0.03152912,  0.08794557, -0.08190262, -0.03765785,
         0.23954882, -0.00476521, -0.15300529, -0.14343345, -0.3391588 ,
         0.00436147, -0.1062618 , -0.03340941, -0.03215582,  0.14501673,
        -0.0273582 , -0.06784916,  0.00409547,  0.09369118,  0.14055185,
         0.0816379 , -0.13477232, -0.01249036,  0.03170796, -0.095968  ,
         0.1299902 ,  0.13285547, -0.02901495, -0.19045506,  0.05008983,
         0.06999357,  0.06491143,  0.02245773, -0.02320031, -0.23702239,
         0.06812254,  0.09915963,  0.13749203, -0.17594048,  0.19762382,
        -0.12925228,  0.10616541,  0.20641492, -0.03672215,  0.19910851,
         0.06596702, -0.00398363, -0.08205791, -0.20634133,  0.06164137,
        -0.05473821,  0.00345039, -0.14491071,  0.30450103, -0.04048162,
         0.05160059,  0.03070004,  0.26621598,  0.1998656 ,  0.0441063 ,
         0.19887276,  0.13527401, -0.00874124,  0.03615938,  0.30547354,
         0.19101025,  0.11101167, -0.19483934,  0.0595747 , -0.09837298],
       dtype=float32),
 array([-0.20105669,  0.14648351,  0.0325936 ,  0.02402721,  0.00350213,
        -0.47396666,  0.12992966,  0.65081966, -0.1657021 , -0.06688585,
        -0.18455063, -0.2010999 , -0.11513948,  0.07107248,  0.07246746,
        -0.1393371 , -0.04952712, -0.39426187, -0.03395934, -0.54342836,
         0.19631669,  0.2171984 ,  0.10540756, -0.10204795, -0.10385588,
        -0.07527038, -0.29308683, -0.2630675 , -0.3100114 ,  0.01713092,
         0.32277572,  0.04731856,  0.14496747, -0.1291109 , -0.05015373,
         0.36185873, -0.00301738, -0.23329291, -0.22615148, -0.52298474,
        -0.00083522, -0.15701705, -0.05248139, -0.05182951,  0.23271792,
        -0.02344953, -0.09903158,  0.00944331,  0.14228131,  0.22256814,
         0.13159978, -0.19904909, -0.02114028,  0.04571357, -0.14676253,
         0.18744172,  0.20007865, -0.05398212, -0.30317286,  0.08252503,
         0.09909172,  0.1066593 ,  0.02345271, -0.04623399, -0.3642924 ,
         0.10673101,  0.14795536,  0.21522546, -0.26905343,  0.30175862,
        -0.19395696,  0.15275127,  0.31765807, -0.05325861,  0.30343187,
         0.1006944 ,  0.00429243, -0.1188987 , -0.31986725,  0.09297344,
        -0.07715086,  0.00785396, -0.22687127,  0.46263072, -0.03823791,
         0.07460624,  0.04904816,  0.41596574,  0.29928613,  0.07112976,
         0.30144376,  0.20043358, -0.009936  ,  0.05990329,  0.4777075 ,
         0.29818347,  0.16354026, -0.29859465,  0.08638094, -0.15480474],
       dtype=float32),
 array([-0.2450817 ,  0.17801847,  0.04745736,  0.02633227,  0.00764654,
        -0.5566313 ,  0.14971033,  0.777229  , -0.20006205, -0.08637198,
        -0.21623836, -0.23430942, -0.12311454,  0.08101748,  0.09055202,
        -0.16606593, -0.04747811, -0.4605582 , -0.04539996, -0.65204483,
         0.22271182,  0.2614211 ,  0.12048923, -0.11581305, -0.12530306,
        -0.09470677, -0.35339832, -0.3096339 , -0.3702445 ,  0.02762272,
         0.38308376,  0.05086004,  0.17455705, -0.167891  , -0.06452283,
         0.44300538, -0.00739228, -0.2896012 , -0.27055508, -0.6309061 ,
         0.0055912 , -0.19011556, -0.05348243, -0.06101121,  0.27180114,
        -0.04219818, -0.1151267 ,  0.01139305,  0.16678444,  0.25744554,
         0.15662912, -0.25149193, -0.02897094,  0.05863357, -0.18128039,
         0.22418419,  0.23663647, -0.05615022, -0.36230788,  0.09760091,
         0.11469007,  0.12564419,  0.03059927, -0.04000893, -0.431303  ,
         0.1308968 ,  0.18430156,  0.2568207 , -0.32840392,  0.36084655,
        -0.23000552,  0.18209738,  0.37777102, -0.06330021,  0.36917037,
         0.11952439, -0.00444758, -0.13749827, -0.37894586,  0.10992983,
        -0.09598211,  0.00769289, -0.26814878,  0.5630611 , -0.0612605 ,
         0.09886156,  0.06009466,  0.50238   ,  0.35805324,  0.07941747,
         0.3571889 ,  0.23706342, -0.00177498,  0.07536756,  0.5678318 ,
         0.3542124 ,  0.19338554, -0.35818142,  0.10941934, -0.18557209],
       dtype=float32),
 array([-0.20824654,  0.1533706 ,  0.04664137,  0.01850649,  0.01411561,
        -0.47507542,  0.12759677,  0.6466767 , -0.17413875, -0.06534967,
        -0.18309265, -0.21067992, -0.10263847,  0.07149316,  0.0847216 ,
        -0.14447781, -0.04026032, -0.3930886 , -0.02568368, -0.54420775,
         0.1830246 ,  0.21850947,  0.09212241, -0.09904899, -0.10344835,
        -0.08143474, -0.3026638 , -0.27284008, -0.32456833,  0.01426576,
         0.33356515,  0.04599494,  0.13934891, -0.13118672, -0.05832141,
         0.3727187 , -0.0160028 , -0.23765591, -0.21845862, -0.53339857,
         0.01061429, -0.17315872, -0.05385767, -0.04459976,  0.2193695 ,
        -0.04515179, -0.10394149,  0.00959847,  0.14693293,  0.21736684,
         0.13541129, -0.21436253, -0.02091855,  0.05720251, -0.16367479,
         0.20744808,  0.20719413, -0.04486074, -0.29891342,  0.08263356,
         0.10321269,  0.10007439,  0.02707139, -0.03356222, -0.36587653,
         0.11061982,  0.15489182,  0.21165463, -0.2807265 ,  0.31026414,
        -0.19980207,  0.16667448,  0.32573384, -0.05967145,  0.32141516,
         0.10535014, -0.0029947 , -0.12476379, -0.3239085 ,  0.09441868,
        -0.08445626,  0.0029305 , -0.2246845 ,  0.47985706, -0.0652899 ,
         0.07606743,  0.04333195,  0.41865554,  0.3250967 ,  0.07570188,
         0.30608934,  0.21238467, -0.01060585,  0.06012037,  0.4794488 ,
         0.30117336,  0.17009959, -0.3047263 ,  0.10147437, -0.15937054],
       dtype=float32),
 array([-0.2640796 ,  0.19162478,  0.05404598,  0.02653762,  0.01394823,
        -0.60962635,  0.16400678,  0.8358438 , -0.21869828, -0.08397412,
        -0.2419573 , -0.2631769 , -0.1365536 ,  0.09497122,  0.10596225,
        -0.17638497, -0.05504552, -0.50587064, -0.04146368, -0.7115746 ,
         0.2458884 ,  0.28534213,  0.1272    , -0.12846707, -0.12862101,
        -0.10068224, -0.3815585 , -0.34190515, -0.402517  ,  0.03163483,
         0.4284422 ,  0.060052  ,  0.18705963, -0.17507535, -0.07370477,
         0.47441795, -0.01418335, -0.30543223, -0.2849641 , -0.6857385 ,
         0.0024724 , -0.2107818 , -0.06481633, -0.05585727,  0.29420397,
        -0.04399683, -0.12912874,  0.01239471,  0.18733473,  0.2787865 ,
         0.16555376, -0.2740469 , -0.03090793,  0.07007781, -0.19918011,
         0.25455382,  0.26134357, -0.05970461, -0.38926637,  0.10963807,
         0.13490663,  0.13273828,  0.03329303, -0.043283  , -0.46864882,
         0.14291662,  0.19959378,  0.28439713, -0.35767594,  0.4026091 ,
        -0.24798335,  0.20820934,  0.41246232, -0.07201585,  0.40684512,
         0.12863152, -0.00382023, -0.15506954, -0.41400287,  0.1164551 ,
        -0.10460907,  0.00111516, -0.29346457,  0.61449605, -0.067721  ,
         0.0979819 ,  0.05544177,  0.5385164 ,  0.40346584,  0.0848965 ,
         0.39844498,  0.27173582, -0.00916103,  0.08238325,  0.6099649 ,
         0.3855914 ,  0.21745646, -0.39024684,  0.12491252, -0.20072198],
       dtype=float32),
 array([-0.25655246,  0.18271628,  0.04765103,  0.02626089,  0.01009854,
        -0.5913457 ,  0.1580484 ,  0.8180826 , -0.2063914 , -0.08677682,
        -0.23284698, -0.2504463 , -0.13745116,  0.0903846 ,  0.09857473,
        -0.16732898, -0.06028318, -0.4956703 , -0.04366658, -0.687938  ,
         0.24386606,  0.27832127,  0.12924218, -0.12295415, -0.1337469 ,
        -0.09137564, -0.36620846, -0.32932308, -0.38504454,  0.03165733,
         0.40673083,  0.05721906,  0.18614244, -0.16822456, -0.0680275 ,
         0.4621772 , -0.01097349, -0.297708  , -0.2834329 , -0.6586158 ,
         0.00332354, -0.20212235, -0.06000046, -0.05981215,  0.29279545,
        -0.03590119, -0.1251729 ,  0.01008861,  0.17428829,  0.27347115,
         0.16441558, -0.25807756, -0.02375638,  0.05985095, -0.1840298 ,
         0.23779568,  0.2536014 , -0.06179113, -0.37837413,  0.10447411,
         0.12482373,  0.13417476,  0.03056039, -0.04339026, -0.45488068,
         0.13588469,  0.19130117,  0.27807248, -0.3405093 ,  0.383341  ,
        -0.23719619,  0.19255279,  0.39894745, -0.0714592 ,  0.390475  ,
         0.11948521, -0.00172845, -0.14973374, -0.3996772 ,  0.11138893,
        -0.09689435,  0.00540712, -0.2899503 ,  0.58895683, -0.05327296,
         0.09724188,  0.05985736,  0.5223833 ,  0.37924796,  0.07940661,
         0.38131067,  0.25523365, -0.00466858,  0.08346856,  0.59608114,
         0.3731017 ,  0.20468603, -0.374591  ,  0.11378738, -0.19122754],
       dtype=float32),
 array([-1.55797765e-01,  1.11066632e-01,  3.29092145e-02,  1.91122051e-02,
         8.45226366e-03, -3.53789359e-01,  9.58540812e-02,  4.78809237e-01,
        -1.32549539e-01, -4.68180478e-02, -1.37090132e-01, -1.55536368e-01,

In [34]:
len(X)

5572

In [35]:
X = np.array(X)

In [41]:
X.shape

(5572, 100)

In [38]:
y = pd.get_dummies(df['label'])
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [39]:
y = y.iloc[:, 1].values

In [40]:
y

array([False, False,  True, ..., False, False, False], shape=(5572,))

In [43]:
df = pd.DataFrame(X)

In [44]:
df.head()

         0         1         2   ...        97        98        99
0 -0.165885  0.124138  0.035017  ... -0.243798  0.084343 -0.130459
1 -0.116900  0.088203  0.025385  ... -0.177206  0.063542 -0.086156
2 -0.194167  0.139488  0.039961  ... -0.285681  0.088776 -0.144053
3 -0.257153  0.193803  0.056564  ... -0.383839  0.125550 -0.206201
4 -0.173010  0.126762  0.036624  ... -0.253180  0.085822 -0.133002

[5 rows x 100 columns]

In [45]:
df.shape

(5572, 100)

In [46]:
X = df

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, random_state=42)

In [49]:
model = classifier.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.97      1.00      0.98       966
        True       0.97      0.79      0.87       149

    accuracy                           0.97      1115
   macro avg       0.97      0.89      0.93      1115
weighted avg       0.97      0.97      0.97      1115

[[962   4]
 [ 31 118]]
0.968609865470852